Repository ITU-BDSA2024-GROUP15/Chirp, pull requests merged in 2024-11, with the labels that each got.

#66 FixTest
  test/Chirp.Web.Tests/IntegrationTests.cs
  test/Chirp.Web.Tests/TestUtilities.cs
  test/Chirp.Web.Tests/UnitTests.cs
Labels: bug, documentation

#68 OAuth_with_Identity
  src/Chirp.Web/Areas/Identity/Pages/Account/ExternalLogin.cshtml
  src/Chirp.Web/Areas/Identity/Pages/Account/ExternalLogin.cshtml.cs
  src/Chirp.Web/Areas/Identity/Pages/Account/Manage/ManageNavPages.cs
  src/Chirp.Web/Areas/Identity/Pages/Account/Manage/_ManageNav.cshtml
  src/Chirp.Web/Areas/Identity/Pages/Account/Manage/_ViewImports.cshtml
  src/Chirp.Web/Areas/Identity/Pages/Account/_ViewImports.cshtml
  src/Chirp.Web/Areas/Identity/Pages/_ValidationScriptsPartial.cshtml
  src/Chirp.Web/Chirp.Web.csproj
  src/Chirp.Web/Pages/Shared/_Layout.cshtml
  src/Chirp.Web/Pages/Shared/_LoginPartial.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
  src/Chirp.Web/Program.cs
  src/Chirp.Web/appsettings.json
Labels: enhancement

#97 TestFollow
  src/Chirp.Web/Chirp.Web.csproj
  test/Chirp.Web.Tests/Chirp.Web.Tests.csproj
  test/Chirp.Web.Tests/IntegrationTests.cs
  test/Chirp.Web.Tests/UnitTests.cs
Labels: testing

#99 FixWarnings
  src/Chirp.Core/Author.cs
  src/Chirp.Infrastructure/Chirp.Repositories/AuthorRepository.cs
  src/Chirp.Infrastructure/Chirp.Repositories/FollowRepository.cs
  src/Chirp.Infrastructure/Chirp.Repositories/IAuthorRepository.cs
  src/Chirp.Infrastructure/Chirp.Services/CheepService.cs
  src/Chirp.Infrastructure/data/DbInitializer.cs
  src/Chirp.Web/Areas/Identity/Pages/Account/ExternalLogin.cshtml
  src/Chirp.Web/Areas/Identity/Pages/Account/ExternalLogin.cshtml.cs
  src/Chirp.Web/Areas/Identity/Pages/Account/Login.cshtml.cs
  src/Chirp.Web/Areas/Identity/Pages/Account/Manage/DeletePersonalData.cshtml.cs
  src/Chirp.Web/Areas/Identity/Pages/Account/Manage/DownloadPersonalData.cshtml.cs
  src/Chirp.Web/Areas/Identity/Pages/Account/Manage/ManageNavPages.cs
  src/Chirp.Web/Areas/Identity/Pages/Account/Manage/PersonalData.cshtml.cs
  src/Chirp.Web/Areas/Identity/Pages/Account/Register.cshtml.cs
  src/Chirp.Web/Pages/Public.cshtml
  src/Chirp.Web/Pages/Public.cshtml.cs
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
  src/Chirp.Web/Program.cs
  test/Chirp.Web.Tests/TestUtilities.cs
Labels: bug

#107 deleteUser
  src/Chirp.Infrastructure/Chirp.Repositories/FollowRepository.cs
  src/Chirp.Infrastructure/Chirp.Repositories/IFollowRepository.cs
  src/Chirp.Infrastructure/Chirp.Services/CheepService.cs
  src/Chirp.Web/Areas/Identity/Pages/Account/Manage/DeletePersonalData.cshtml.cs
  src/Chirp.Web/Areas/Identity/Pages/Account/Manage/Index.cshtml
  src/Chirp.Web/Areas/Identity/Pages/Account/Manage/_ManageNav.cshtml
  src/Chirp.Web/wwwroot/css/style.css
  test/Chirp.Web.Tests/IntegrationTests.cs
  test/PlaywrightTests/End-To-End-Test.cs
  test/PlaywrightTests/PlaywrightTests.csproj
Labels: enhancement
