Repository ITU-BDSA2024-GROUP15/Chirp, pull requests merged in 2024-12, with the labels that each got.

#122 feat: Like data now gets deleted when account is deleted
  src/Chirp.Infrastructure/Chirp.Repositories/CheepRepository.cs
  src/Chirp.Infrastructure/Chirp.Repositories/ICheepRepository.cs
  src/Chirp.Infrastructure/Chirp.Services/CheepService.cs
  src/Chirp.Web/Areas/Identity/Pages/Account/Manage/DeletePersonalData.cshtml.cs
  test/Chirp.Web.Tests/IntegrationTests.cs
Labels: enhancement

#138 Fixed pagination
  src/Chirp.Web/Pages/Public.cshtml
  src/Chirp.Web/Pages/Public.cshtml.cs
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
Labels: bug

#139 ShowLikesOnAboutMe
  src/Chirp.Infrastructure/Chirp.Repositories/CheepRepository.cs
  src/Chirp.Infrastructure/Chirp.Repositories/ICheepRepository.cs
  src/Chirp.Infrastructure/Chirp.Services/ChirpService.cs
  src/Chirp.Web/Areas/Identity/Pages/Account/Manage/Index.cshtml
  src/Chirp.Web/Areas/Identity/Pages/Account/Manage/Index.cshtml.cs
Labels: enhancement

#144 ShowTopLikes
  src/Chirp.Infrastructure/Chirp.Repositories/CheepRepository.cs
  src/Chirp.Infrastructure/Chirp.Repositories/ICheepRepository.cs
  src/Chirp.Infrastructure/Chirp.Services/ChirpService.cs
  src/Chirp.Web/Pages/Shared/_LoginPartial.cshtml
  src/Chirp.Web/Pages/TopCheeps.cshtml
  src/Chirp.Web/Pages/TopCheeps.cshtml.cs
Labels: enhancement

#150 Playwright-fix
  test/PlaywrightTests/End-To-End-Test.cs
  test/PlaywrightTests/UnitTest1.cs
Labels: testing

#151 More unittests for CheepRepository
  src/Chirp.Infrastructure/Chirp.Repositories/CheepRepository.cs
  test/Chirp.Web.Tests/IntegrationTests.cs
  test/Chirp.Web.Tests/UnitTests.cs
Labels: testing

#157 Unit Tests for AuthorRepo
  src/Chirp.Infrastructure/Chirp.Repositories/AuthorRepository.cs
  src/Chirp.Infrastructure/Chirp.Repositories/CheepRepository.cs
  test/Chirp.Web.Tests/UnitTests.cs
Labels: testing

#158 Like-Cheep-playwright
  test/PlaywrightTests/End-To-End-Test.cs
Labels: testing

#159 Follow repo unit tests
  test/Chirp.Web.Tests/UnitTests.cs
Labels: testing

#163 RefactorRazorPages
  src/Chirp.Web/Pages/AuthorTimeline.cshtml
  src/Chirp.Web/Pages/AuthorTimeline.cshtml.cs
  src/Chirp.Web/Pages/Public.cshtml
  src/Chirp.Web/Pages/Public.cshtml.cs
  src/Chirp.Web/Pages/Shared/Components/Timeline/Timeline.cshtml
  src/Chirp.Web/Pages/Shared/TimelineModel.cs
  src/Chirp.Web/Pages/Shared/_LoginPartial.cshtml
  src/Chirp.Web/Pages/TopCheeps.cshtml
  src/Chirp.Web/Pages/TopCheeps.cshtml.cs
  src/Chirp.Web/Pages/UserTimeline.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
  src/Chirp.Web/ViewComponents/TimelineViewComponent.cs
Labels: refactoring

#164 ChirpServiceTests
  test/Chirp.Web.Tests/UnitTests.cs
  test/PlaywrightTests/End-To-End-Test.cs
Labels: testing

#169 fix-warnings-in-integrationTests
  test/Chirp.Web.Tests/IntegrationTests.cs
Labels: testing

#167 Delete your own cheeps
  src/Chirp.Infrastructure/Chirp.Repositories/CheepRepository.cs
  src/Chirp.Infrastructure/Chirp.Repositories/IAuthorRepository.cs
  src/Chirp.Infrastructure/Chirp.Repositories/ICheepRepository.cs
  src/Chirp.Infrastructure/Chirp.Services/ChirpService.cs
  src/Chirp.Web/Pages/Shared/Components/Timeline/Timeline.cshtml
  src/Chirp.Web/Pages/Shared/TimelineModel.cs
  src/Chirp.Web/wwwroot/css/style.css
  test/Chirp.Web.Tests/UnitTests.cs
  test/PlaywrightTests/End-To-End-Test.cs
Labels: enhancement

#172 MoveDTOs
  src/Chirp.Infrastructure/Chirp.Services/ChirpService.cs
  src/Chirp.Infrastructure/DataTransferObjects/AuthorDTO.cs
  src/Chirp.Infrastructure/DataTransferObjects/CheepDto.cs
  src/Chirp.Infrastructure/DataTransferObjects/FollowDTO.cs
  src/Chirp.Web/Areas/Identity/Pages/Account/Manage/Index.cshtml.cs
  src/Chirp.Web/Pages/Shared/TimelineModel.cs
  src/Chirp.Web/Program.cs
Labels: refactoring

#175 FixedQueryForLikes
  src/Chirp.Infrastructure/Chirp.Services/ChirpService.cs
Labels: enhancement
