Repository ITU-BDSA2024-GROUP15/Chirp, pull requests merged in 2024-10, with the labels that each got.

#33 origin/DomainModel
  src/Chirp.Razor/Cheep.cs
  src/Chirp.Razor/CheepDTO.cs
  src/Chirp.Razor/CheepRepository.cs
  src/Chirp.Razor/CheepService.cs
  src/Chirp.Razor/DBFacade.cs
  src/Chirp.Razor/Datamodel/Author.cs
  src/Chirp.Razor/Datamodel/Cheep.cs
  src/Chirp.Razor/Datamodel/CheepDBContext.cs
  src/Chirp.Razor/ICheepRepository.cs
  src/Chirp.Razor/Migrations/20241002222904_InitialDBSchema.Designer.cs
  src/Chirp.Razor/Migrations/20241002222904_InitialDBSchema.cs
  src/Chirp.Razor/Migrations/CheepDBContextModelSnapshot.cs
  src/Chirp.Razor/Pages/Public.cshtml
  src/Chirp.Razor/Pages/Public.cshtml.cs
  src/Chirp.Razor/Pages/UserTimeline.cshtml
  src/Chirp.Razor/Pages/UserTimeline.cshtml.cs
  src/Chirp.Razor/Program.cs
  src/Chirp.Razor/data/Cheep.db
  src/Chirp.Razor/data/DbInitializer.cs
  test/Chirp.Razor.Tests/UnitTests.cs
Labels: refactoring

#41 FixWarnings
  src/Chirp.Razor/CheepDTO.cs
  src/Chirp.Razor/CheepDto.cs
  src/Chirp.Razor/CheepRepository.cs
  src/Chirp.Razor/CheepService.cs
  src/Chirp.Razor/Datamodel/Author.cs
  src/Chirp.Razor/Datamodel/Cheep.cs
  src/Chirp.Razor/Datamodel/CheepDBContext.cs
  src/Chirp.Razor/Migrations/20241002222904_InitialDBSchema.Designer.cs
  src/Chirp.Razor/Migrations/CheepDBContextModelSnapshot.cs
  src/Chirp.Razor/Pages/Public.cshtml
  src/Chirp.Razor/Pages/Public.cshtml.cs
  src/Chirp.Razor/Pages/UserTimeline.cshtml
  src/Chirp.Razor/Pages/UserTimeline.cshtml.cs
  src/Chirp.Razor/Program.cs
  src/Chirp.Razor/data/DbInitializer.cs
  src/Chirp.Razor/data/chirp.db
  test/Chirp.Razor.Tests/UnitTests.cs
Labels: bug

#42 Added AuthorRepository.cs
  src/Chirp.Razor/AuthorRepository.cs
  src/Chirp.Razor/CheepRepository.cs
  src/Chirp.Razor/CheepService.cs
  src/Chirp.Razor/Datamodel/Author.cs
  src/Chirp.Razor/IAuthorRepository.cs
Labels: enhancement

#44 Adding_cheeps
  src/Chirp.Infrastructure/Chirp.Repositories/AuthorRepository.cs
  src/Chirp.Infrastructure/Chirp.Repositories/CheepRepository.cs
  src/Chirp.Infrastructure/Chirp.Repositories/IAuthorRepository.cs
  src/Chirp.Infrastructure/Chirp.Repositories/ICheepRepository.cs
  src/Chirp.Infrastructure/Chirp.Services/CheepService.cs
Labels: enhancement
